

version: 2

models:
  - name: stg_ga_global
    description: >
      Calcul global de toutes les sessions à partir de la Roll Up property GA. Le calcul est 
      effectué sur l'ensembledes pays EU hors RU et Ile de Beaute pour lesquels les 
      données de trafic sont à récupérer dans cybersource. 

models:
  - name: stg_app_global
    description: >
     Calcul du trafic global App à partir des données cybersource. Ce calcul prend en compte tous 
     les pays y compris RU. Le trafic est calculé à partir de la table cbs_ga_fb_aggregated.

models:
  - name: stg_not_app_global
    description: >
      Calcul du trafic global Web RU et Ile de beauté. Le trafic est calculé à partir des données 
      cybersource -> table cbs_ga_fb_aggregated. La requête fait un filtre sur RU et prend tout le
      trafic Hors App.

models:
  - name: stg_global_cybersource
    description: >
      Trafic global tout source confondu ( Website et APP ) et tout marché inclus ( y compris RU et Ile 
      de beauté )

models:
  - name: stg_sessions_retrieved
    description: >
      Calcul du trafic redressé. Méthode : Vérifier la méthode avec Alexandre et l'équipe Weba. 

models:
  - name: stg_forecast
    description: >
      Collecte des données du trafic forecast tout pays confondus. Les données viennent 
      du fichier ci dessous : 
      "**[Forecast Data](https://docs.google.com/spreadsheets/d/1qWUj5UtHc0dYjip6kdMwuQ7gDFypfV06wYRotMv0l10/edit#gid=880889007)**"

models:
  - name: stg_adwords
    description: >
      Consolidation des données Adwords par pays et par device. Les taux de change utilisés 
      sont ceux de la table stg_taux_change.

models:
  - name: stg_facebook
    description: >
      Consolidation des données facebook et instagram par pays et par device. Les taux de 
      change utilisés sont ceux de la table stg_taux_change.      
                          

