version: 2

sources:
  - name: ga_data
    loader: BigQuery
    schema: '136443498'
    database: s4a-ga-raw-data-prd
    tables:
      - name: ga_sessions_*
        tags: ['Google Analytics']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"

  - name: cy_data
    loader: BigQuery
    schema:  cybersource
    database: s4a-digital-dwh-prd
    tables:
      - name: cbs_ga_fb_aggregated
        tags: ['Cybersource']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"      
      - name: cbs_reports_PART
        tags: ['Google Analytics']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"      

  - name: forecast
    loader: BigQuery
    schema:  cybersource
    database: s4a-digital-dwh-prd
    tables:
      - name: forecast_data
        tags: ['Cybersource']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"      

  - name: piano
    loader: BigQuery
    schema: piano
    database: s4a-ga-raw-data-prd
    tables:
      - name: raw_export_partitioned  
        tags: ['Piano Analytics']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"

  - name: de
    loader: BigQuery
    schema:  eme_media_data
    database: s4a-digital-dwh-prd
    tables:
      - name: de_data_crm
        tags: ['CRM Database']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Isabelle"

  - name: funnel
    loader: BigQuery
    schema: funnel_data
    database: s4a-digital-dwh-prd
    tables:
      - name: funnel_data_*
        tags: ['Funnel Media Data']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"
      - name: funnel_account_orga    
        tags: ['Funnel Media Data']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Youri"

  - name: cac_mvp
    loader: BigQuery
    schema: cac_reporting
    database: s4a-digital-dwh-prd
    tables:
      - name: MVP_BY_Months_Channel_Support_BQ
        owner: Eme Data
        tags: ['CAC MVP']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Isabelle"
      - name: MVP_BY_Week_Channel_Support_BQ
        owner: Eme Data
        tags: ['CAC MVP']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Isabelle"

  - name: ga4
    loader: BigQuery
    schema:  eme_media_data
    database: s4a-digital-dwh-prd
    tables:
      - name: ga4_data
        tags: ['GA4 Dara']
        meta:
          contains_pii: false
          owner : "Web Data Team -> Isabelle"


